### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/DynamicPullRequests#1]
- [x] Create a special branch that only runs on PR's, named based on the PR number.
- [x] Create a regular action that runs all the time ("Dev")
- [x] Add PR RG
